version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: my-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  next:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-next-app
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
